### ISSUE TITLE
Mettre le lien du dépôt dans la partie "Comment ?" de about.php

### ISSUE THREAD

**Issue by Outpox** [Outpox/Stan#2]
Je sais pas si tu avais prévu de le faire ou que tu n'as pas eu le temps, mais ce n'est pas un dépôt privé donc on s'en tape non ? :)

**Comment by CBRPLX** [comment]
Ouais s’pas bête, j’avais pas pensé. :)
Du coup je l’ai fais :P

**Comment by Outpox** [comment]
:+1:
