### ISSUE TITLE
Unable to retrieve location [...]

### ISSUE THREAD

**Issue by Outpox** [Outpox/Stan#3]
![image](https://cloud.githubusercontent.com/assets/3439246/8003657/b399a40c-0b79-11e5-9311-338eeedd8713.png)

Je vais donc regarder.

**Comment by Outpox** [comment]
Bon ça marche sur le téléphone, je pense que le soucis est lié au proxy de mon boulot ou une connerie du genre. Si tu peux confirmer que ça marche en desktop de ton côté tu peux fermer l'issue ;)

**Comment by CBRPLX** [comment]
J'étais justement en train d'écrire que ça marchait ici, et que j'avais bien mis une clé API :)
