### ISSUE TITLE
Spam sites référents sur analytics

### ISSUE THREAD

**Issue by Outpox** [Outpox/Stan#4]
![image](https://cloud.githubusercontent.com/assets/3439246/8003916/b3b86c28-0b7b-11e5-8b86-230db6f1a708.png)

Il faut ajouter les urls dans des filtres d'exclusions via le panel admin (chose que je ne peux pas faire). :-)

**Comment by CBRPLX** [comment]
C'est fait, à vérifier de temps en temps pour rajouter les nouveaux spams :)
